version: "3.9"

services:
  app:
    build: ./
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: